[package]
name = "raytracing-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bvh = "0.7.2"
glam = "0.24.0"
image = "0.24.6"
indicatif = "0.17.3"
num = "0.4.0"
rand = "0.8.5"
rayon = "1.7.0"
